Repository pedrorrivero/pr-toolbox, pull requests merged in 2023-06, with the labels that each got.

#3 feat(frequencies): add function to convert counts to quasi distribution
  pr_toolbox/quantum/results/frequencies.py
  test/unit/quantum/results/test_frequencies.py
Labels: feature, PL-3

#2 feat(frequencies): add support for QuasiDistribution type
  pr_toolbox/quantum/results/__init__.py
  pr_toolbox/quantum/results/frequencies.py
  pr_toolbox/quantum/results/reckoning.py
  test/unit/quantum/results/test_frequencies.py
Labels: feature, PL-3

#4 fix(frequencies): fix plural name in counts_to_quasi_dist
  pr_toolbox/quantum/results/frequencies.py
  test/unit/quantum/results/test_frequencies.py
Labels: bug, PL-4

#1 feat(reckoning): add support for QuasiDistribution type
  pr_toolbox/quantum/results/reckoning.py
  test/unit/quantum/results/test_reckoning.py
Labels: feature, PL-2
